name: Container Image
on:
  push:
    branches:
      - 'master'
    tags:        
      - '**'

env:
  debian_version: bullseye

jobs:
  build:
    name: Build container image and push it to registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse version
        id: get-version
        uses: battila7/get-version-action@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push - testing
        uses: docker/build-push-action@v3
        if: ${{ !steps.get-version.outputs.is-semver }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            DEBIAN_VERSION=${{ env.debian_version }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      
      - name: Build and push - pre-release
        uses: docker/build-push-action@v3
        if: ${{ steps.get-version.outputs.is-semver && steps.get-version.outputs.prerelease != '' }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            DEBIAN_VERSION=${{ steps.get-version.outputs.major }}.${{ steps.get-version.outputs.minor }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.get-version.outputs.version-without-v }}
      
      - name: Build and push - stable
        uses: docker/build-push-action@v3
        if: ${{ steps.get-version.outputs.is-semver && steps.get-version.outputs.prerelease == '' }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            DEBIAN_VERSION=${{ steps.get-version.outputs.major }}.${{ steps.get-version.outputs.minor }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.get-version.outputs.version-without-v }}
            ghcr.io/${{ github.repository }}:${{ steps.get-version.outputs.major }}.${{ steps.get-version.outputs.minor }}.${{ steps.get-version.outputs.patch }}
            ghcr.io/${{ github.repository }}:${{ steps.get-version.outputs.major }}.${{ steps.get-version.outputs.minor }}
            ghcr.io/${{ github.repository }}:${{ steps.get-version.outputs.major }}
            ghcr.io/${{ github.repository }}:${{ env.debian_version }}